version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run dev

artifacts:
  files:
    - '**/*'
  base-directory: dist